ProyectoPoliza/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoPoliza.Models;
using ProyectoPoliza.Servicios.Contrato;
using ProyectoPoliza.Servicios.Implementacion;

namespace ProyectoPoliza.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private readonly IGenericService<Cliente> _clienteService;
        public ClientesController(IGenericService<Cliente> clienteService)
        {
            _clienteService = clienteService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaClientes()
        {
            List<Cliente> _lista = await _clienteService.List();

            //IQueryable<Cliente> queryContactoSQL = await _ClienteService.ObtenerTodos();

            //List<ClienteVM> _lista = queryContactoSQL
            //                                         .Select(c => new ClienteVM()
            //                                         {
            //                                             IdCliente = c.IdCliente,
            //                                             Nombre = c.Nombre,
            //                                             Cedula = c.Cedula,
            //                                             Telefono = c.Telefono,
            //                                             Cargo = c.Cargo,
            //                                             Eliminado = c.Eliminado.Value
            //                                         }).ToList();

            return StatusCode(StatusCodes.Status200OK, _lista);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarCliente([FromBody] Cliente model)
        {
            bool _resultado = await _clienteService.Save(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]
        public async Task<IActionResult> EditarCliente([FromBody] Cliente model)
        {
            bool _resultado = await _clienteService.Edit(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]

        public async Task<IActionResult> EliminarCliente(int idCliente)
        {
            bool _resultado = await _clienteService.Delete(idCliente);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }
    }
}

ProyectoPoliza/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ProyectoPoliza.Models;
using ProyectoPoliza.Servicios.Contrato;
namespace ProyectoPoliza.Controllers
{
    [Authorize]
    public class EmpleadosController : Controller
    {
        private readonly IGenericService<Empleado> _empleadoService;
        public EmpleadosController(IGenericService<Empleado> empleadoService)
        {
            _empleadoService = empleadoService;
        }
    
        public IActionResult Index()
        {
            return View();
        }
                
        [HttpGet]
        public async Task<IActionResult> ListaEmpleados()
        {
            List<Empleado> _lista = await _empleadoService.List();

            //IQueryable<Empleado> queryContactoSQL = await _empleadoService.ObtenerTodos();

            //List<EmpleadoVM> _lista = queryContactoSQL
            //                                         .Select(c => new EmpleadoVM()
            //                                         {
            //                                             IdEmpleado = c.IdEmpleado,
            //                                             Nombre = c.Nombre,
            //                                             Cedula = c.Cedula,
            //                                             Telefono = c.Telefono,
            //                                             Cargo = c.Cargo,
            //                                             Eliminado = c.Eliminado.Value
            //                                         }).ToList();

            return StatusCode(StatusCodes.Status200OK, _lista);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarEmpleado([FromBody] Empleado model)
        {
            bool _resultado = await _empleadoService.Save(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]
        public async Task<IActionResult> EditarEmpleado([FromBody] Empleado model)
        {
            bool _resultado = await _empleadoService.Edit(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new{ valor = _resultado, msg = "ok"});
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]

        public async Task<IActionResult> EliminarEmpleado(int idEmopleado)
        {
            bool _resultado = await _empleadoService.Delete(idEmopleado);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }
    }
}

ProyectoPoliza/Controllers/PolizasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoPoliza.Models;
using ProyectoPoliza.Servicios.Contrato;
using ProyectoPoliza.Servicios.Implementacion;

namespace ProyectoPoliza.Controllers
{
    [Authorize]
    public class PolizasController : Controller
    {
        private readonly IGenericService<Poliza> _polizaService;
        public PolizasController(IGenericService<Poliza> empleadoService)
        {
            _polizaService = empleadoService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaPoliza()
        {
            List<Poliza> _lista = await _polizaService.List();

            return StatusCode(StatusCodes.Status200OK, _lista);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarPoliza([FromBody] Poliza model)
        {
            bool _resultado = await _polizaService.Save(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]
        public async Task<IActionResult> EditarPoliza([FromBody] Poliza model)
        {
            bool _resultado = await _polizaService.Edit(model);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }

        [HttpPut]

        public async Task<IActionResult> EliminarPoliza(int idPoliza)
        {
            bool _resultado = await _polizaService.Delete(idPoliza);

            if (_resultado)
            {
                return StatusCode(StatusCodes.Status200OK, new { valor = _resultado, msg = "ok" });
            }
            else
            {
                return StatusCode(StatusCodes.Status500InternalServerError, new { valor = _resultado, msg = "error" });
            }
        }
    }
}

ProyectoPoliza/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoPoliza.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProyectoPoliza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CuentasPorCobrar - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    <link href="~/lib/datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary  sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">CASNIC</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
           @* <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>*@

            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Usuarios")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("Index","Empleados")">Empleados</a>
                    </div>
                </div>
            </li>
            <!-- Nav Item - Mantenedor Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="bi bi-briefcase-fill"></i>
                    <span>Mantenedor</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Clientes")">Clientes</a>
                        <a class="collapse-item" href="@Url.Action("Index","Circulaciones")">Circulaciones</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Cuentas por cobrar Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Polizas de seguro</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Polizas")">Registro de Polizas</a>
                        <a class="collapse-item" href="@Url.Action("Index","DetallePolizas")">Historial de Polizas</a>
                    </div>
                </div>
            </li>



            <!-- Nav Item - Reportes Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="reporte_venta.html">Reporte de Polizas</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="@Url.Action("CerrarSesion","Home")" id="userDropdown" role="button"
                                aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Salir </span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                
                                @*<div class="dropdown-divider" ></div>
                                <a  class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                                  
                                        Salir
                                    
                                </a>*@
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; CASNIC 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    <script src="~/lib/datepicker/bootstrap-datepicker.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>